title: Pavol Hejný
tagline: Personal page of Pavol Hejný
description: >-
    Personal page of Pavol Hejný

# Note: For more configuration options @see https://github.com/githubtraining/github-pages/blob/main/config.yml

theme: no-style-please # Note: For more themes @see http://jekyllthemes.org/
