#!/usr/bin/env ts-node

import chalk from 'chalk';
import commander from 'commander';
import { writeFile } from 'fs/promises';
import { join } from 'path';
import spaceTrim from 'spacetrim';
import { commit } from '../0-utils/commit';
import { findProjectsOnGithub } from './findProjectsOnGithub';

main();

async function main() {
    console.info(chalk.bgBlue(`🏭 Generate projects`));

    const program = new commander.Command();
    program.option('--commit', `Commit after generate`, false);

    program.parse(process.argv);
    const { commit: isCommit } = program.opts();

    const projects = await findProjectsOnGithub();

    // TODO: Remove date - but for now it is useful for testing Github action
    const projectsContent = spaceTrim(
        (block) => `
        # 👨‍🏭 Projets

        <!-- ⚠️ WARNING: This was generated by generate-projects at ${new Date().toISOString()}-->
        All projects I have worked on:

        ${block(
            projects
                .map(({ name, url, organization }) =>
                    spaceTrim(`
                        - [${name}](${url})
                    `),
                )
                .join('\n'),
        )}
    
    `,
    );

    await writeFile(join(process.cwd(), 'documents/projects.en.md'), projectsContent, 'utf8');

    if (isCommit) {
        await commit({ projectPath: process.cwd(), message: `🏭 Generate projects` });
    }

    process.exit(0);
}

/**.
 * TODO: Also include project from here https://docs.google.com/spreadsheets/d/1tGQBOknXYAnn9rDCE7KsbpyapVb6NKdwiONwPJl3DF0/edit?usp=sharing
 *       - Maybe EVERY project should have a Github page?
 */
